default:
  host: ytbCreator.mysql.pythonanywhere-services.com
  user: ytbCreator
  password: 1111
  database: YoutubeDATA1
  connect_timeout: 10
  read_timeout: 10
  autocommit: false
  ssl: null

ssh:
  host: 127.0.0.1
  user: ytbCreator
  password: 111
  database: YoutubeDATA1
  connect_timeout: 10
  read_timeout: 10
  autocommit: false
  ssl: null
