default:
  host: test.mysql.pythonanywhere-services.com
  user: testUser
  password: testDBPassword
  database: testDatabase
  connect_timeout: 10
  read_timeout: 10
  autocommit: false
  ssl: null

ssh:
  host: 127.0.0.1
  user: testUser
  password: testDBPassword
  database: testDatabase
  connect_timeout: 10
  read_timeout: 10
  autocommit: false
  ssl: null
